/**
 * A transaction generated by the recurring-transaction engine (`recurring_rule_id`
 * set) is RECURRING - subscriptions, rent, insurance, etc. A transaction created
 * from a user-authored one-off planned transaction (`planned_transaction_id` set)
 * is ONE_TIME - the user explicitly scheduled this specific event, not a rule.
 * Everything else is UNKNOWN: existing data has no reliable signal either way,
 * and guessing ONE_TIME would misrepresent ordinary transactions as non-recurring
 * one-off spending to an AI reader.
 */
export type ExpenseNature = "RECURRING" | "ONE_TIME" | "UNKNOWN";

export function classifyExpenseNature(transaction: Readonly<{ recurringRuleId?: string; plannedTransactionId?: string }>): ExpenseNature {
  if (transaction.recurringRuleId) return "RECURRING";
  if (transaction.plannedTransactionId) return "ONE_TIME";
  return "UNKNOWN";
}

export type ExpenseNatureSource = "UNSET" | "MANUAL" | "SUGGESTED";
export type ResolvedExpenseNature = ExpenseNature | "IRREGULAR" | "EXCEPTIONAL";

/**
 * A MANUAL value the user explicitly chose always wins - it carries intent
 * the derived signal can't see (e.g. "this subscription-looking charge was
 * actually a one-off gift"). Anything else falls back to classifyExpenseNature
 * so existing UNSET data keeps behaving exactly as before this feature shipped.
 */
export function resolveExpenseNature(transaction: Readonly<{
  recurringRuleId?: string;
  plannedTransactionId?: string;
  expenseNatureUser?: ResolvedExpenseNature;
  expenseNatureSource?: ExpenseNatureSource;
}>): ResolvedExpenseNature {
  if (transaction.expenseNatureSource === "MANUAL" && transaction.expenseNatureUser) {
    return transaction.expenseNatureUser;
  }
  return classifyExpenseNature(transaction);
}
