/**
 * A transaction generated by the recurring-transaction engine (`recurring_rule_id`
 * set) is RECURRING - subscriptions, rent, insurance, etc. A transaction created
 * from a user-authored one-off planned transaction (`planned_transaction_id` set)
 * is ONE_TIME - the user explicitly scheduled this specific event, not a rule.
 * Everything else is UNKNOWN: existing data has no reliable signal either way,
 * and guessing ONE_TIME would misrepresent ordinary transactions as non-recurring
 * one-off spending to an AI reader.
 */
export type ExpenseNature = "RECURRING" | "ONE_TIME" | "UNKNOWN";

export function classifyExpenseNature(transaction: Readonly<{ recurringRuleId?: string; plannedTransactionId?: string }>): ExpenseNature {
  if (transaction.recurringRuleId) return "RECURRING";
  if (transaction.plannedTransactionId) return "ONE_TIME";
  return "UNKNOWN";
}
