import { describe, expect, it } from "vitest";

import {
  createRecurringTransactionService,
  type GeneratedOccurrence,
  type RecurringInput,
  type RecurringRepository,
  type RecurringRule,
} from "@/server/recurring/service";

const userId = "user-a";
const account = { id: "account-a", userId, isActive: true };
const category = { id: "category-a", userId, isActive: true };
const input: RecurringInput = {
  type: "EXPENSE",
  amount: 14_900,
  currency: "KRW",
  accountId: account.id,
  categoryId: category.id,
  frequency: "MONTHLY",
  intervalCount: 1,
  dayOfMonth: 15,
  startDate: "2026-08-15",
  confirmationMode: "AUTO_CONFIRM",
};

function repository(options: {
  accounts?: ReadonlyArray<typeof account>;
  categories?: ReadonlyArray<typeof category>;
  generated?: GeneratedOccurrence[];
} = {}): RecurringRepository {
  const accounts = options.accounts ?? [account];
  const categories = options.categories ?? [category];
  const rules: RecurringRule[] = [];

  return {
    findAccount: async (_userId, id) => accounts.find((item) => item.id === id) ?? null,
    findCategory: async (_userId, id) => categories.find((item) => item.id === id) ?? null,
    createRule: async (ownerId, value) => {
      const rule = { id: "rule-1", userId: ownerId, isActive: true, ...value };
      rules.push(rule);
      return rule;
    },
    listRules: async () => rules,
    updateRule: async (ownerId, id, value) => {
      const existing = rules.find((rule) => rule.id === id && rule.userId === ownerId);
      if (!existing) return null;
      const updated = { ...existing, ...value };
      rules.splice(rules.indexOf(existing), 1, updated);
      return updated;
    },
    deactivateRule: async (ownerId, id) => {
      const existing = rules.find((rule) => rule.id === id && rule.userId === ownerId);
      if (!existing) return false;
      existing.isActive = false;
      return true;
    },
    generateDue: async () => options.generated ?? [],
  };
}

describe("recurring transaction service", () => {
  it("rejects a recurring rule that references an account outside the current user", async () => {
    const service = createRecurringTransactionService(repository());

    await expect(service.create(userId, { ...input, accountId: "other-user-account" })).rejects.toThrow("active account owned");
  });

  it("creates an owned active rule with its start date as the next run date", async () => {
    const service = createRecurringTransactionService(repository());

    await expect(service.create(userId, input)).resolves.toMatchObject({
      id: "rule-1",
      userId,
      isActive: true,
      nextRunDate: "2026-08-15",
    });
  });

  it.each([
    ["a fractional amount", { amount: 14_900.5 }, "amount"],
    ["an unsafe amount", { amount: Number.MAX_SAFE_INTEGER + 1 }, "amount"],
    ["a foreign currency", { currency: "USD" }, "KRW"],
    ["an invalid start date", { startDate: "2026-02-30" }, "date"],
    ["an end date before the start date", { endDate: "2026-08-14" }, "endDate"],
    ["a nonpositive interval", { intervalCount: 0 }, "intervalCount"],
    ["a monthly rule without a day", { dayOfMonth: undefined }, "dayOfMonth"],
    ["a monthly rule with an out-of-range day", { dayOfMonth: 32 }, "dayOfMonth"],
  ])("rejects %s", async (_label, changes, message) => {
    const service = createRecurringTransactionService(repository());

    await expect(service.create(userId, { ...input, ...changes })).rejects.toThrow(message);
  });

  it("rejects an inactive category", async () => {
    const service = createRecurringTransactionService(repository({ categories: [{ ...category, isActive: false }] }));

    await expect(service.create(userId, input)).rejects.toThrow("active category owned");
  });

  it("lists rules scoped to the supplied user", async () => {
    const service = createRecurringTransactionService(repository());
    await service.create(userId, input);

    await expect(service.list(userId)).resolves.toHaveLength(1);
  });

  it("validates a replacement rule before updating it", async () => {
    const service = createRecurringTransactionService(repository());
    await service.create(userId, input);

    await expect(service.update(userId, "rule-1", { ...input, currency: "USD" })).rejects.toThrow("KRW");
  });

  it("rejects deactivation of a rule outside the current user", async () => {
    const service = createRecurringTransactionService(repository());

    await expect(service.deactivate(userId, "other-user-rule")).rejects.toThrow("recurring rule not found");
  });

  it("returns occurrences generated by the repository", async () => {
    const generated: GeneratedOccurrence[] = [{ ruleId: "rule-1", occurrenceDate: "2026-08-15", status: "CONFIRMED" }];
    const service = createRecurringTransactionService(repository({ generated }));

    await expect(service.generateDue(userId, "2026-08-15")).resolves.toEqual(generated);
  });
});
